feat: add login layout and init EditTexts and button in LoginActivity
SergeiMikhailovskii/RPPBA pull request #1
Opened 2020-03-17 08:38 UTC by glebannister

2020-03-17 08:41 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/login/LoginActivity.java
> +        buttonOnClick();
не выноси в отдельный метод, а прям в onCreate пиши:
```
 singInButton.setOnClickListener(new View.OnClickListener() {
             @Override
             public void onClick(View v) {
                 //TODO authorization
             }
         });
```

2020-03-17 08:43 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/login/LoginActivity.java
> +        singInButton.setOnClickListener(new View.OnClickListener() {
посмотри, как добавить Java8 в проект, а то я забыл. Тогда все анонимные классы на лямбду заменятся и лучше выглядеть

2020-03-17 08:46 UTC, SergeiMikhailovskii requested changes

2020-03-17 08:46 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/login/LoginActivity.java
> +                //TODO authorization
доставай пока логин и пароль из editText и просто в логи кидай:

```
password = edit.getText();
Log.i(password)
```

2020-03-17 08:46 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +<LinearLayout
Перепили на `ConstraintLayout` и почитай про `Guidelines` в нем. Тогда получше на телефонах с разными размерами смотреться будет, а то такая разметка поедет на любом другом

2020-03-17 09:19 UTC, SergeiMikhailovskii requested changes

2020-03-17 09:19 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/login/LoginActivity.java
> +        singInButton.setOnClickListener(new View.OnClickListener() {
у тебя входе здесь должно было предложить заменить на лямбду, не?

2020-03-17 09:20 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +    android:orientation="vertical"
это вроде убрать можно

2020-03-17 09:21 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintGuide_begin="57dp" />
установи гайдлайн не в dp, а в %

2020-03-17 09:26 UTC, SergeiMikhailovskii requested changes

2020-03-17 09:26 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +    <ImageView
чет ты тут намудрил. Тебе надо было сделать 4 гайдлайна: 2 по бокам от картинки, и потом привязываешь start картинки к правому гайдлайну, end к левому. И 2 по бокам от инпутов. к ним привязываешь инпуты и кнопки. и тогда тебе надо будет оставить ток 
```
app:layout_constraintTop_toTopOf="parent"
app:layout_constraintStart_toStartOf="@+id/guideline"
app:layout_constraintEnd_toEndOf="@+id/guideline1"
``` 
ну и маржины какие-то

2020-03-17 09:26 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +
попробуй крч снести весь слой, сначала расставить гайдлайны в процентах, а потом уже элементы расставляй

2020-03-17 14:41 UTC, SergeiMikhailovskii requested changes

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintHorizontal_bias="0.115"
эту строку убрать можешь вообще

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          app:layout_constraintBottom_toBottomOf="parent"
смотри, у тебя у картинки top должен быть привязан к top parent, start к guideline2, end к guideline3, а снизу ее вообще ни к чему привязывать не надо, потому что в этом нету смысла

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintVertical_bias="1.0" />
это тоже убирай

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintStart_toStartOf="@+id/guideline2"
и добавь еще строку `app:layout_constraintDimensionRatio="1:1"`, она ширину=высоте картинке сделает

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_width="300dp"
если у тебя он привязан по бокам к гайдлайнам, то можешь ставить ширину 0 и вьюга автоматически между гайдлайнами растянется

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          app:layout_constraintTop_toTopOf="parent" />
вот в этом и суть constraint layout: ты должен привязывать не к parent а ко вьюги, которая находится ближе. В данном случае, тебе надо привязать верх edittext к низу картинки, и тогда marginTop будет меньше, где-то 20-30

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_marginBottom="356dp"
это тоже убирай, вместе с привязкой bottom к parent

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_width="300dp"
то же самое, ширина 0

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_marginTop="400dp"
топ к боттом эдита, который выше

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_marginBottom="306dp"
это убирай

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          app:layout_constraintBottom_toBottomOf="parent"
и это

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          app:layout_constraintTop_toTopOf="parent" />
то же самое, тут топ не пережат должен быть

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_width="300dp"
ширина 0

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_marginTop="600dp"
убирай

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:layout_marginBottom="21dp"
сделай лучше 20 хотя бы, или 24, а то 21 такое себе

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          app:layout_constraintTop_toTopOf="parent" />
тут топ не нужен

2020-03-17 14:41 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
> +        app:layout_constraintGuide_percent="0.11" />
сделай проценты покрасивее. например для гайдлайнов, которые кнопку оборачивают 20% и 80%, а которые эдиты 10% и 90%

2020-03-18 08:25 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_login.xml
>          android:hint="@string/login"
почти ок, только замени вот это: `app:layout_constraintTop_toTopOf="@id/car_image_view" ` на `app:layout_constraintTop_toBottomOf="@id/car_image_view"`, т.к. картинка может быть больше, чем твой отступ в 230дп, и тогда эдит наедет на нее. и то же самое сделай для Эдита пароля

2020-03-18 08:44 UTC, merged

2020-03-18 08:50 UTC, glebannister commented
Я сразу заметил привязку к Верху только для логина и картинки, пофискил и залил
Но там ещё такая же фигня была с двумя эдитами, я вот только что новый комит залил

  
>Среда, 18 марта 2020, 11:44 +03:00 от Sergei Mikhailovskii <notifications@github.com>:
> 
> 
>Merged  #1 into master.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Глеб Игнатович
 

2020-03-18 08:55 UTC, glebannister commented
Я вижу пул реквест уже закрыт. Может мне скачать заново проект и в мастере это справить?

  
>Среда, 18 марта 2020, 11:50 +03:00 от Глеб Игнатович <igi2000@inbox.ru>:
> 
>Я сразу заметил привязку к Верху только для логина и картинки, пофискил и залил
>Но там ещё такая же фигня была с двумя эдитами, я вот только что новый комит залил
>
> 
>>Среда, 18 марта 2020, 11:44 +03:00 от Sergei Mikhailovskii < notifications@github.com >:
>> 
>> 
>>Merged  #1 into master.
>>—
>>You are receiving this because you authored the thread.
>>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
> 
> 
>--
>Глеб Игнатович
>  
 
 
--
Глеб Игнатович
 

2020-03-18 08:57 UTC, SergeiMikhailovskii commented
я чет пропустил, да. переключись в студии на мастер, выкачай его, пофикси, и прям в мастер коммить и пушь потом