Gleb products
SergeiMikhailovskii/RPPBA pull request #4
Opened 2020-03-24 07:46 UTC by glebannister

2020-03-24 08:01 UTC, SergeiMikhailovskii requested changes

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +        View itemView = LayoutInflater.from(parent.getContext()).inflate(R.layout.stocks_element, parent, false);
переименуй со `stocks_element` на `stock_element`. так эстетичнее))

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +        holder.amount.setText(stockItems.get(position).getAmount()+"");
сделай так: `StockItem stockItem = stockItems.get(position)`, и потом обращайся к этому объекту. а то я сделал фигово, лучше будет каждый раз не к массиву обращаться, а к объекту

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/main/MainActivity.java
> +        StockFragment stockFragment = new StockFragment();
Верни назад название фрагмента `MaterialsFragment`. Ну и презентеру и контракту тоже соответственно. Потому что фрагмент у нас отвечает именно за материалы на складе

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/main/MainActivity.java
> +        startTransaction.add(R.id.fragment_layout, stockFragment);
ну и название лэйаута тоже в материалы верни

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/main/MainActivity.java
> +                case R.id.stockItems:
и тут

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/stocks/ProductFragment.java
> +        swipeRefreshLayout = view.findViewById(R.id.swipe_refresh);
впихни тут пустую строку, красивее смотреться код будет

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/stocks/StockContract.java
> +        void onMaterialsLoaded(List<StockItem> stockItems);
тут можешь переименовать `stockItems` в `materials`. потому что да, массив сток айтемов, но эти сток айтемы в данном случае именно материалы

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/stocks/ProductContract.java
> +        void onProductsLoaded(List<StockItem> stockItems);
переименуй `stockItems` в `products`

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/stocks/StockFragment.java
> +public class StockFragment extends Fragment implements StockContract.MaterialsView, StockAdapter.OnItemClickListener {
`StockFragment` -> `MaterialsFragment`
`StockContract` -> `MaterialsContract`

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/stocks/StockFragment.java
> +    private StockPresenter presenter = new StockPresenter();
`StockPresenter` -> `MaterialsPresenter`

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/stocks/StockFragment.java
> +        View view = inflater.inflate(R.layout.fragment_stocks, container, false);
fragment_materials

2020-03-24 08:01 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/fragment_stocks.xml
> +    tools:context=".ui.stocks.StockFragment">
и поменяй структуру проекта. В package ui есть package materials: там фрагмент, контракт и презентер для материалов.  В package ui есть package products: там фрагмент, контракт и презентер для продуктов.

2020-03-24 08:48 UTC, SergeiMikhailovskii requested changes
Все ок почти, ток добавь в `MainActivity` навигацию к твоему фрагменту, как я это сделал со своим. И в хмл `stock_element` сделай, чтобы количество товара было жирным шрифтом. посмотри, какой атрибут юзается в названии продукта и впихни его в количество

2020-03-24 16:03 UTC, SergeiMikhailovskii requested changes
Еще ток ща заметил, что ты адаптер не инициализируешь в своем фрагменте нигде. из-за этого крашится будет. посмотри, как это в моем фрагменте сделано.

2020-03-25 07:37 UTC, SergeiMikhailovskii requested changes
Ещё ты забыл поменять названия в презентете. Они у тебя такие же, как и в материалах, а должны быть другие. поменяй пж

2020-03-25 08:41 UTC, glebannister commented
Серёга, не очень понял, здесь названия поменять?
productsList.add(new StockItem("https://s3-alpha-sig.figma.com/img/de92/669d/1f1dd0b493cda7ba55446e552d34c5e8?Expires=1585526400&Signature=bgKxyNXUD4N5Dr6BnsnUHzkHljxodP9bxjTGvBaxyYAkcAtLrSie9ux9yBk~qm2c5yxPBvGVex68yuzfyMwcg8Y9Ck1x-ZLnu5pG~izkE3VQcDjopssTiY6NNsQFVGhBimDGXxWTtx1vYYpcBreBBNgpvMP6NUXHNn9YCYMgRg5-WDEs9cBOlMvR-aKeI448G322XEPKcnzpj8xTorrAYatG5u~txzjMwsd4LRPH3~55owm2rOuVWEO1SeFTB7z5~rK7N187AC6K61OinXWCQiImbHGqIGkHRk70xaLb3J5bu6czm9iwPPCTSc65QrZti0qRtWm8nygr-FMFeW4sIw__&Key-Pair-Id=APKAINTVSUGEWH5XD5UA",
        "Pen form",
        "Standart",
        100,
        new ArrayList<>())); 
>Среда, 25 марта 2020, 10:37 +03:00 от Sergei Mikhailovskii <notifications@github.com>:
> 
> 
>@SergeiMikhailovskii requested changes on this pull request.
>Ещё ты забыл поменять названия в презентете. Они у тебя такие же, как и в материалах, а должны быть другие. поменяй пж
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Глеб Игнатович
 

2020-03-25 08:53 UTC, SergeiMikhailovskii commented
да, там в фигме другие названия

2020-03-25 11:23 UTC, SergeiMikhailovskii approved these changes

2020-03-25 11:23 UTC, merged