feat: Manufacture layout
SergeiMikhailovskii/RPPBA pull request #5
Opened 2020-03-30 09:50 UTC by glebannister

2020-03-30 12:47 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/manufacture_layout.xml
> +<?xml version="1.0" encoding="utf-8"?>
удали этот файл, у тебя ж разметка есть уже

2020-03-30 12:47 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/manufacture/ManufactureFragment.java
> +        private Button sendButton;
переименуй названия кнопок, например sendToManufactureButton и getFromManufactureButton, а то названия не оч

2020-03-30 12:48 UTC, SergeiMikhailovskii requested changes

2020-03-30 12:48 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/manufacture/ManufactureFragment.java
> +
и сделай автоформат ( ctrl+alt+L)

2020-03-30 17:03 UTC, glebannister commented
Для чего именно?

  
>Понедельник, 30 марта 2020, 15:48 +03:00 от Sergei Mikhailovskii <notifications@github.com>:
> 
> 
>@SergeiMikhailovskii requested changes on this pull request.
>----------------------------------------------------------------------
>In  app/src/main/java/com/bsuir/rppba/ui/manufacture/ManufactureFragment.java :
>> +        private Button sendButton;
>
>+        private Button getButton;
>
>+
>
>+
>
>+        @Nullable
>
>+        @Override
>
>+        public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
>
>+            View view = inflater.inflate(R.layout.manufacture_fragment, container, false);
>
>+            sendButton = view.findViewById(R.id.sendButton);
>
>+            getButton = view.findViewById(R.id.getButton);
>
>+            sendButton.setOnClickListener(v -> Toast.makeText(getContext(), "Send", Toast.LENGTH_SHORT).show());
>
>+            getButton.setOnClickListener(v -> Toast.makeText(getContext(), "Get", Toast.LENGTH_SHORT).show());
>
>+            return view;
>
>+        }
>
>+    }
>
>+
>
>
>и сделай автоформат ( ctrl+alt+L)
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Глеб Игнатович
 

2020-03-30 17:38 UTC, SergeiMikhailovskii commented
> Для чего именно?  
> Понедельник, 30 марта 2020, 15:48 +03:00 от Sergei Mikhailovskii ***@***.***>:     @SergeiMikhailovskii requested changes on this pull request. ---------------------------------------------------------------------- In app/src/main/java/com/bsuir/rppba/ui/manufacture/ManufactureFragment.java : > + private Button sendButton; + private Button getButton; + + + @nullable + @override + public View onCreateView(@nonnull LayoutInflater inflater, @nullable ViewGroup container, @nullable Bundle savedInstanceState) { + View view = inflater.inflate(R.layout.manufacture_fragment, container, false); + sendButton = view.findViewById(R.id.sendButton); + getButton = view.findViewById(R.id.getButton); + sendButton.setOnClickListener(v -> Toast.makeText(getContext(), "Send", Toast.LENGTH_SHORT).show()); + getButton.setOnClickListener(v -> Toast.makeText(getContext(), "Get", Toast.LENGTH_SHORT).show()); + return view; + } + } + и сделай автоформат ( ctrl+alt+L) — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub , or unsubscribe .
>     -- Глеб Игнатович

для всех файлов, которые ты в этом коммите создал/менял. просто открываешь файл и жмешь ctrl alt l. https://medium.com/mindorks/11-android-studio-shortcuts-every-android-developer-must-know-a153e736e611

2020-03-31 06:54 UTC, SergeiMikhailovskii requested changes

2020-03-31 06:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/main/MainActivity.java
> +                case R.id.manufacture:
ты в кейсах пропустил break, поправь

2020-03-31 06:54 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/manufacture_fragment.xml
> +        android:text="@string/getButton"
поменяй стили этой кнопки. сделай ей background белый, а границы @color/colorBlue

2020-03-31 06:54 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/manufacture_fragment.xml
> +        android:textColor="@color/cardview_light_background"
лучше так цвета не юзай. попробуй @android:color вроде, там белый будет, а то так непонятно, что это за кардвью какой-то

2020-03-31 14:19 UTC, SergeiMikhailovskii requested changes

2020-03-31 14:19 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/manufacture_fragment.xml
> +        android:background="@color/colorWhite"
посмотри, как убрать тени у кнопки и сделай ей границу @color/colorBlue

2020-03-31 15:40 UTC, SergeiMikhailovskii approved these changes

2020-03-31 15:40 UTC, merged