Product info g
SergeiMikhailovskii/RPPBA pull request #7
Opened 2020-04-06 07:30 UTC by glebannister

2020-04-09 12:17 UTC, glebannister commented
Серёг, чекни плиз. 
+ у меня возник трабл с ProductInfoPresenter

2020-04-14 08:38 UTC, SergeiMikhailovskii requested changes

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.productsinfo.ProductInfoActivity"></activity>
сделай вместо такого тэга <></> такой < />. Здесь нет необходимости в явном открытом и закрытом тэге

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/AndroidManifest.xml
>          <activity android:name=".ui.login.LoginActivity">
пока мне не оч нравится, что это так выглядит) Хотелось бы, чтобы не было такого огромного отступа между элементами списка
![image](https://user-images.githubusercontent.com/33265881/79202376-33c96780-7e42-11ea-8630-716547269d18.png)

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +        holder.itemView.setOnClickListener(v -> {
Здесь надо клик не на весь элемент, а ток на кнопку `move`

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +    public interface OnItemClickListener{
пройдись автоформатом по всем файлам

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +            infoTextViewPlace = itemView.findViewById(R.id.infoTextViewPlace);
называй такие переменные либо `textViewInfoPlace`, либо `infoPlaceTextView`. Я чаще второй вариант использую. Я не оч понимаю, зачем в переменной есть слово info. Мне кажется оно лишним, но если ты считаешь, что так правильно, то оставляй. Потому что в твоем случае, тип переменной (`TextView`) не сразу заметен

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +            infoTextViewAmount = itemView.findViewById(R.id.infoTextViewAmount);
тут то же самое

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +            infoButton = itemView.findViewById(R.id.infoButton);
кнопку тоже переименуй. Я бы `moveButton` назвал

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/main/MainActivity.java
> +                case R.id.productsInfo:
Посмотри еще раз в дизайне пж, там на этот скрин попадаешь не через таб в ботом навигации, а через нажатие на элемент списка

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/productsinfo/ProductInfoActivity.java
> +    private SwipeRefreshLayout swipeRefreshLayout;
мне кажется, что на этом скрине не надо свайп рефреш, но если ты считаешь, что надо, то опять же ок, оставляй

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/productsinfo/ProductInfoActivity.java
> +        // productInfoRecyclerView.addItemDecoration(new DividerItemDecoration(Objects.requireNonNull(DividerItemDecoration.VERTICAL, this));
декоратор оставляй, он надо

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/productsinfo/ProductInfoActivity.java
> +    public void showLoadingIndicator(boolean value) {
посмотри, как для свайп рефреша сделан лоадинг на других скринах

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/productsinfo/ProductInfoPresenter.java
> +        places.add(new Place("Unsorted", R.integer.A100, R.integer.MaxLimit));
не выноси здесь в ресурсы. на данном этапе нашей приложухи, это мб и ок, хотя тоже и не оч правильно, а когда данные будут приходить с апихи, то они никак в наших ресурсах не окажутся

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_product_info.xml
> +        android:id="@+id/penImageView"
переименуй на `productImageView`, например. здесь не всегда будет ручка

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_product_info.xml
> +    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
а зачем ты  в свайп рефреш обернул ток список? надо было все оборачивать, но лучше убери его вообще

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_product_info.xml
> +            android:layout_width="0dp"
ресайклер должен быть шириной matchParent, это уже элементы в нем на гайдлайнах подвязаны

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/product_info_item.xml
> +        android:layout_height="55dp"
у них высота должны быть match_parent

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/res/menu/bottom_navigation_menu.xml
> +    <item
это убирай

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/res/values/integers.xml
> +    <integer name="A100">100</integer>
это все тоже

2020-04-14 08:38 UTC, SergeiMikhailovskii commented on app/src/main/res/values/strings.xml
> +    <string name="A1">A1</string>
это все тоже

2020-04-15 18:04 UTC, SergeiMikhailovskii requested changes
Из общего:
- Пройдись по всем файлам автоформатом
- Запусти приложуху, пройдись по всем скринам, посмотри, чтобы нигде не крашилось
- Пройдись по всем файлам, посмотри, где студия предлагает какие-то автоподсказки, используй их

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +    private List<Place> placeArrayList = new ArrayList<>();
переименуй на places

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +        holder.moveButton.setOnClickListener(v -> {
v переименуй во view

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +    private OnUserClickListener listener;
а зачем ты здесь изменил на OnUserClickListener? Верни OnItemClickListener. Тут же юзер ни при чем

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +        void onUserClick(int position);
здесь соответственно тоже, не юзер, а айтем

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +    public StockAdapter() {
а зачем тут конструктор с пустым телом? Либо в нем что-то должно быть, либо можешь убрать его вообще

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +    public void setOnClickUserListener(OnUserClickListener listener){
я бы не менял логику лисенера в адаптере, и передавал бы его в конструктор, а не сетил отдельно

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +        return new ViewHolder(itemView, listener);
а зачем ты еще и лисенер во вью холдер передаешь? норм же в бинде было

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +    class ViewHolder extends RecyclerView.ViewHolder  {
тут статик класс должен быть

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +            itemView.setOnClickListener(new View.OnClickListener() {
ну и соответственно, если обработка клика в онБиндВьюХолдере будет, то здесь это все не надо

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/materials/MaterialFragment.java
> +public class MaterialFragment extends Fragment implements MaterialContract.MaterialsView{
как было норм, лучше не менять

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/materials/MaterialFragment.java
> +    private Context context;
а зачем ты тут контектовую переменную объявил, если не юзаешь ее нигде?

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/materials/MaterialFragment.java
> +        adapter = new StockAdapter();
оставь как было тут

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/materials/MaterialFragment.java
> +        adapter.setOnClickUserListener(new StockAdapter.OnUserClickListener() {
и тогда это не надо

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/materials/MaterialFragment.java
> -    public void onItemClicked(int position, StockItem materials) {
оставляй вот это, ток клик другой теперь

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/products/ProductFragment.java
> +public class ProductFragment extends Fragment implements ProductContract.ProductView {
и здесь оставляй имплементацию интерфейса

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/products/ProductFragment.java
> +    private Context context;
опять же, контекст убирай

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/products/ProductFragment.java
> +        adapter = new StockAdapter();
конструктор тот же оставляй

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/products/ProductFragment.java
> +        adapter.setOnClickUserListener(position -> startActivity(new Intent(getContext(), ProductInfoActivity.class)));
это убирай

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/productsinfo/ProductInfoActivity.java
> +        swipeRefreshLayout.setRefreshing(true);
там немного по другому сделано. в твоем случае индикатор будет вечно крутиться

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/res/layout/activity_product_info.xml
> +    <androidx.swiperefreshlayout.widget.SwipeRefreshLayout
В свайп рефреш оберни весь лэйаут

2020-04-15 18:04 UTC, SergeiMikhailovskii commented on app/src/main/res/values/strings.xml
> +    <string name="Unsorted">Unsorted</string>
эти ресурсы убирай

2020-04-19 17:31 UTC, moonmvm commented
Глеб! Соберись!!!!!!!

2020-04-23 17:54 UTC, SergeiMikhailovskii requested changes

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/AndroidManifest.xml
> -
не заметил, ты тут еще мой кусок вырезал, верни его. будь повнимательнее с мерж конфликтами

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +        view.amountTextView.setText(place.getAmount()+"");
сейчас это уже не исправляй, потом мб, если время будет почитаешь про локализацию ресурсов с числами именно, и потом мб заменишь

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +    public ProductInfoAdapter(OnItemClickListener onItemClickListener){
все равно в этом файле не везде автоформат, заюзай его еще раз

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/ProductInfoAdapter.java
> +            if (view.getAdapterPosition() != RecyclerView.NO_POSITION){
`getAdapterPosition` deprecated, поэтому посмотри и замени на то, что предлагают разрабы вместо этого метода

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +    private ArrayList<StockItem> stockItems;
здесь все же лучше оставь, как было. вот почему тип переменной лучше лист https://stackoverflow.com/a/2279059/10597533

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +        Log.d("Tag", "bind, position = " + position);
логи для дебага убирай, их в мастере быть не должно

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +            if (holder.getAdapterPosition() != RecyclerView.NO_POSITION){
как и выше, замени deprecated метод

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +import static androidx.constraintlayout.widget.Constraints.TAG;
вот это непонятно что, убери

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +import android.content.Intent;
это убери, раз нигде не юзается

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/adapter/StockAdapter.java
> +import com.bsuir.rppba.ui.productsinfo.ProductInfoActivity;
и это

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/materials/MaterialFragment.java
> +    private ArrayList<StockItem> stockItems;
тут тоже сделай тип не ArrayList, а List

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/java/com/bsuir/rppba/ui/productsinfo/ProductInfoActivity.java
> +            Log.i("ID", String.valueOf(id));//тут я чекнул правильное ли id достаёт
раз значение приходит, то можешь лог убирать

2020-04-23 17:54 UTC, SergeiMikhailovskii commented on app/src/main/res/menu/bottom_navigation_menu.xml
> +        android:id="@+id/productsInfo"
все еще не убрал

2020-04-24 18:13 UTC, SergeiMikhailovskii approved these changes

2020-04-24 18:13 UTC, merged